Modulo_GestionC/Models/Impuesto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo_GestionC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Impuesto
    {
        public int IdImp { get; set; }
        [Required]
        public string NombreImpuesto { get; set; }
        [Required]
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        [Required]
        public Nullable<double> Monto { get; set; }
        [Required]
        public System.DateTime FechaPago { get; set; }
        [Required]
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        [Required]
        public string TipoImpuesto { get; set; }
        [Required]
        public Nullable<int> ClientePerteneciente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}

Modulo_GestionC/Controllers/ClienteController.cs
using Modulo_GestionC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Modulo_GestionC.Controllers
{
   [Authorize (Roles="CPN,Empleado")]
    public class ClienteController : Controller
    {
        // GET: Cliente
        [Authorize(Roles = "CPN,Empleado,Administrador")]
        public ActionResult Index(string searchString, string sortOrder)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                var Clientes = from s in db.Cliente
                               select s;
                if (!String.IsNullOrEmpty(searchString))
                {
                    Clientes = Clientes.Where(s => s.CUIT.ToString().Contains(searchString)
                                           || s.NombreContribuyente.Contains(searchString) ||
                                           s.TipoCliente.Contains(searchString) ||
                                           s.RegimenImpositivo.NombreRegimenImpositivo.Contains(searchString) ||
                                           s.RegimenImpositivo.Categoria.Contains(searchString));
                }
                switch (sortOrder)
                {
                    case "name_desc":
                        Clientes = Clientes.OrderByDescending(s => s.NombreContribuyente);
                        break;

                    default:
                        Clientes = Clientes.OrderBy(s => s.NombreContribuyente);
                        break;
                }
                return View(Clientes.ToList());
            }

        }
        //crear cliente
        public ActionResult Crear()
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Cliente cl)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                if (db.Cliente.Any(p => p.CUIT == cl.CUIT))
                {
                    ModelState.AddModelError("CUITI", "Ya existe CUIT ingresado");
                }
                if (ModelState.IsValid)
                {
                    try
                    {
                        cl.FechaRegistro = DateTime.Now;
                        db.Cliente.Add(cl);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {

                        ModelState.AddModelError("ERROR AL AGREGAR Cliente", ex);
                        return View();
                    }
                }
                return View();
            }

        }
        //Editar cliente
        public ActionResult Edit(int id)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Cliente pac = db.Cliente.Where(p => p.IdCliente == id).FirstOrDefault();

                return View(pac);
            }
        }

        // POST:/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Cliente p)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Cliente pac = db.Cliente.Where(p1 => p1.IdCliente== id).FirstOrDefault();

                pac.NombreContribuyente = p.NombreContribuyente;
                pac.CUIT = p.CUIT;

                pac.Direccion = p.Direccion;
                pac.Telefono = p.Telefono;
                pac.Mail = p.Mail;
                pac.TipoCliente = p.TipoCliente;
                pac.RegimenImpositivoPerteneciente = p.RegimenImpositivoPerteneciente;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        //detallar cliente
        public ActionResult Details(int id)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Cliente pac = db.Cliente.Find(id);
                return View(pac);

            }
        }
        //eliminar cliente
        public ActionResult Delete(int? id)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Cliente pac = db.Cliente.Find(id);
                if (pac == null)
                {
                    return HttpNotFound();
                }
                return View(pac);
            }


        }

        // POST: Cliente/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Cliente pac = db.Cliente.Find(id);
                db.Cliente.Remove(pac);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
        }
        //combo
        public ActionResult ListarRI()
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                return PartialView(db.RegimenImpositivo.ToList());
            }
        }
        // mostrar datos ri
        public static string RI(int? cRI)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {

                string pacientes = db.RegimenImpositivo.Find(cRI).NombreRegimenImpositivo +
                    " " + db.RegimenImpositivo.Find(cRI).Categoria + ".";
                return pacientes;

            }
        }
        // fin

    }
}

Modulo_GestionC/Controllers/ImpuestoController.cs
using Modulo_GestionC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Modulo_GestionC.Controllers
{
    [Authorize(Roles = "CPN,Empleado")]
    public class ImpuestoController : Controller
    {
        public ActionResult Index(string searchString)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                var Impuestos = from s in db.Impuesto
                                select s;
                if (!String.IsNullOrEmpty(searchString))
                {
                    Impuestos = Impuestos.Where(s => s.NombreImpuesto.Contains(searchString));
                }

                return View(Impuestos.ToList());
            }

        }
        //crearImpuesto
        public ActionResult Crear()
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                return View();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Impuesto imp)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {

                if (ModelState.IsValid)
                {
                    try
                    {
                        imp.FechaRegistro = DateTime.Now;
                        db.Impuesto.Add(imp);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {

                        ModelState.AddModelError("ERROR AL AGREGARImpuesto", ex);
                        return View();
                    }
                }
                return View();
            }

        }
        //EditarImpuesto
        public ActionResult Edit(int id)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Impuesto pac = db.Impuesto.Where(p => p.IdImp == id).FirstOrDefault();

                return View(pac);
            }
        }

        // POST:/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Impuesto p)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Impuesto pac = db.Impuesto.Where(p1 => p1.IdImp == id).FirstOrDefault();

                pac.NombreImpuesto= p.NombreImpuesto;
                pac.FechaVencimiento = p.FechaVencimiento;
                pac.Monto = p.Monto;
                pac.FechaPago = p.FechaPago;
                pac.TipoImpuesto = p.TipoImpuesto;
                pac.ClientePerteneciente = p.ClientePerteneciente;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        //detallarImpuesto
        public ActionResult Details(int id)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Impuesto pac = db.Impuesto.Find(id);
                return View(pac);

            }
        }
        //eliminarImpuesto
        public ActionResult Delete(int? id)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Impuesto pac = db.Impuesto.Find(id);
                if (pac == null)
                {
                    return HttpNotFound();
                }
                return View(pac);
            }


        }

        // POST:Impuesto/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                Impuesto pac = db.Impuesto.Find(id);
                db.Impuesto.Remove(pac);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
        }
        //combo
        public ActionResult ListarCliente()
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                return PartialView(db.Cliente.ToList());
            }
        }
        // mostrar datos ri
        public static string Cliente(int? cc)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {

                string Clientes = db.Cliente.Find(cc).NombreContribuyente +
                    " " + db.Cliente.Find(cc).CUIT.ToString() + " " + db.Cliente.Find(cc).TipoCliente + " " +
                    db.Cliente.Find(cc).RegimenImpositivo.NombreRegimenImpositivo+ " "
                    + db.Cliente.Find(cc).RegimenImpositivo.Categoria + ".";
                return Clientes;

            }
        }
        // fin

    }
}

Modulo_GestionC/Controllers/MostrarTodoController.cs
using Modulo_GestionC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Modulo_GestionC.Controllers
{
    [Authorize(Roles = "CPN,Empleado,Administrador")]
    public class MostrarTodoController : Controller
    {

        public ActionResult Index(string searchString, string sortOrder)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                var Clientes = from s in db.Cliente
                               select s;
                if (!String.IsNullOrEmpty(searchString))
                {
                    Clientes = Clientes.Where(s => s.CUIT.ToString().Contains(searchString)
                                           || s.NombreContribuyente.Contains(searchString) ||
                                           s.TipoCliente.Contains(searchString) ||
                                           s.RegimenImpositivo.NombreRegimenImpositivo.Contains(searchString) ||
                                           s.RegimenImpositivo.Categoria.Contains(searchString));
                }
                switch (sortOrder)
                {
                    case "name_desc":
                        Clientes = Clientes.OrderByDescending(s => s.NombreContribuyente);
                        break;

                    default:
                        Clientes = Clientes.OrderBy(s => s.NombreContribuyente);
                        break;
                }
                return View(Clientes.ToList());
            }

        }
        public ActionResult Impuesto(string searchString)
        {
            using (ContextoModuloG db = new ContextoModuloG())
            {
                var Impuestos = from s in db.Impuesto
                                select s;
                if (!String.IsNullOrEmpty(searchString))
                {
                    Impuestos = Impuestos.Where(s => s.NombreImpuesto.Contains(searchString)||
                    s.Cliente.CUIT.ToString().Contains(searchString)
                                           || s.Cliente.NombreContribuyente.Contains(searchString));
                }

                return View(Impuestos.ToList());
            }

        }
    }
}

Modulo_GestionC/Views/MostrarTodo/Impuesto.cshtml
@model IEnumerable<Modulo_GestionC.Models.Impuesto>

<p>
    @Html.ActionLink("Ir a Impuesto", "Index","Impuesto")
</p>
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.NombreImpuesto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Monto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPago)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoImpuesto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientePerteneciente)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.NombreImpuesto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaVencimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Monto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaPago)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaRegistro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoImpuesto)
        </td>
        <td>
            @Modulo_GestionC.Controllers.ImpuestoController.Cliente(item.ClientePerteneciente)
        </td>
      
    </tr>
}

</table>

Modulo_GestionC/Views/MostrarTodo/Index.cshtml
@model IEnumerable<Modulo_GestionC.Models.Cliente>

@{
    ViewBag.Title = "ShowAll";
}

<h2>Show All</h2>
@using (Html.BeginForm())
{
    <p>
        Buscar por cliente: @Html.TextBox("SearchString")
        <input type="submit" value="Buscar" class="btn btn-success" />
    </p>
}
<p>
    @Html.ActionLink("Ir a Clientes", "Index","Cliente")
</p>
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.NombreContribuyente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CUIT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegimenImpositivoPerteneciente)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.NombreContribuyente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CUIT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaRegistro)
            </td>
            <td>
                @Modulo_GestionC.Controllers.ClienteController.RI(item.RegimenImpositivoPerteneciente)
            </td>
            
        </tr>
    }

</table>
<p>
    @Html.Action("Impuesto")
</p>